# Generated by Django 5.2.8 on 2025-11-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('Management_id', models.AutoField(primary_key=True, serialize=False)),
                ('Management_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=255)),
                ('rfid', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_id',
            new_name='classroom_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_fk',
        ),
        migrations.AddField(
            model_name='class',
            name='scanner_id',
            field=models.CharField(default='Example', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(default='CSIT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='overall_attendance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='rfid',
            field=models.CharField(default='123', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='B', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default='2022'),
            preserve_default=False,
        ),
    ]
