# Generated by Django 5.2.8 on 2025-12-03 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_updateattendancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='taughtcourse',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='taughtcourse',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], default='active', max_length=10)),
                ('qr_code_token', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.teacher')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_scanned', models.BooleanField(default=False)),
                ('rfid_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('qr_scanned', models.BooleanField(default=False)),
                ('qr_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('marked_present_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.attendancesession')),
            ],
            options={
                'ordering': ['-marked_present_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
