# Generated by Django 5.2.8 on 2026-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_rollno_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateattendancerequest',
            name='attendanceType',
            field=models.CharField(choices=[('regular', 'Regular'), ('compensatory', 'Compensatory')], default='regular', max_length=20),
        ),
    ]
