# Generated by Django 5.2.8 on 2026-05-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attendancesession_metadata_fields'),
        ('core', '0016_faceembedding'),
    ]

    operations = [
    ]
