# Generated by Django 5.2.8 on 2026-05-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_attendancesession_attendance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='classes_absent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
