# Generated by Django 5.2.8 on 2026-03-10 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_location_event_venue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registered_at',
            new_name='registration_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='attended',
        ),
        migrations.AddField(
            model_name='registration',
            name='attendance_status',
            field=models.CharField(choices=[('attended', 'Attended'), ('not_attended', 'Not Attended')], default='not_attended', max_length=15),
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
