# Generated by Django 5.2.8 on 2026-03-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_registered_at_registration_registration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registration_date',
            new_name='registered_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='attendance_status',
        ),
        migrations.AddField(
            model_name='registration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ParticipantProfile',
        ),
    ]
