# Generated by Django 5.2.8 on 2026-04-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventadvisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadvisor',
            name='organization',
        ),
    ]
