# Generated by Django 5.2.8 on 2026-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_eventadvisor_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='face_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
