"""
Django settings for FYP_Backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional in some environments
    load_dotenv = None

if load_dotenv is not None:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y5(s6m$eihu0hw^js7j1dfdmposk(l_877=0!b24!*4p-^19ez'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Comma-separated hosts/IPs for dev access (e.g. "localhost,127.0.0.1,192.168.1.10").
_default_allowed_hosts = ['testserver', 'localhost', '127.0.0.1']
_env_allowed_hosts = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if host.strip()]
ALLOWED_HOSTS = _env_allowed_hosts or _default_allowed_hosts
for _host in _default_allowed_hosts:
    if _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

# Base URLs used for event invite-link generation and redirect flows.
DEFAULT_EVENT_BASE_URL = os.environ.get('DEFAULT_EVENT_BASE_URL', 'http://localhost:8000').rstrip('/')
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'http://localhost:5173').rstrip('/')

# External CV module integration for face registration.
CV_MODULE_BASE_URL = os.environ.get('CV_MODULE_BASE_URL', 'http://127.0.0.1:9000').rstrip('/')
CV_MODULE_REGISTER_PATH = os.environ.get('CV_MODULE_REGISTER_PATH', '/register-face/')
CV_MODULE_REGISTER_URL = os.environ.get(
    'CV_MODULE_REGISTER_URL',
    f'{CV_MODULE_BASE_URL}{CV_MODULE_REGISTER_PATH}',
)
CV_MODULE_VERIFY_PATH = os.environ.get('CV_MODULE_VERIFY_PATH', '/verify-face/')
CV_MODULE_VERIFY_URL = os.environ.get(
    'CV_MODULE_VERIFY_URL',
    f'{CV_MODULE_BASE_URL}{CV_MODULE_VERIFY_PATH}',
)
CV_MODULE_TIMEOUT_SECONDS = float(os.environ.get('CV_MODULE_TIMEOUT_SECONDS', '15'))

# CORS – allow the Vite dev server (default port 5173) and any other local frontend
_default_cors_origins = [
    'http://localhost:5173',
    'http://localhost:3000',
    
    'http://127.0.0.1:5173',
    'http://127.0.0.1:3000',
]
_env_cors_origins = [origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()]
CORS_ALLOWED_ORIGINS = _default_cors_origins + _env_cors_origins
if FRONTEND_BASE_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_BASE_URL)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'core.apps.CoreConfig',
    'events.apps.EventsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FYP_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FYP_Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for testing if TESTING environment variable is set
import sys
TESTING = 'test' in sys.argv
USE_SQLITE = os.environ.get('USE_SQLITE', 'True') == 'True'

if TESTING:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
elif USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
                'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'school_db',
            'USER': 'dbuser',
            'PASSWORD': 'dbpass',
            'HOST': 'localhost',  # or DB host/IP
            'PORT': '5433',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL for @login_required decorator
LOGIN_URL = '/api/login/student/'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Simple JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Attendance scanning behavior
# - Default: require both RFID + QR (2FA)
# - For testing: set ATTENDANCE_REQUIRE_RFID=0 to allow QR-only or RFID-only
if TESTING:
    # Keep unit tests deterministic (2FA on by default); tests can override via override_settings.
    ATTENDANCE_REQUIRE_RFID = False
else:
    ATTENDANCE_REQUIRE_RFID = os.environ.get('ATTENDANCE_REQUIRE_RFID', '0').strip().lower() in {
        '1', 'true', 'yes', 'y', 'on'
    }

